### ISSUE TITLE
Errors produced at the HTTP layer. Please try again.

### ISSUE THREAD

**Issue by amirber** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#191] opened 2020-03-19 13:23 UTC
hi
i have this error after upload complete : "Errors produced at the HTTP layer. Please try again." 
what should i do?

**Comment by vineetchoudhary** [comment] 2020-03-19 13:31
Hi @amirber ,

This means DropBoxSDK produce some error. This is something, I can't handle it because DropBoxSDK is completely managed by DropBox Team. I looking for some alternative technics like the auto-restart process if DropBoxSDK produces some error. But right now you've to try again manually. I'm really sorry about any inconvenience.

**Comment by amirber** [comment] 2020-03-19 13:37
thank you for your helping.
what do yo mean about "right now you've to try again manually"?
upload manually to the dropbox?

**Comment by vineetchoudhary** [comment] 2020-06-04 08:02
Hi All,

First of all, thank you very much for using AppBox. I added an automatic retry option for this issue. Also, if this occurs in the latest version (2.9.1) then AppBox will show more details about this.

For one case, I was successfully able to reproduce this issue with the unc0ver IPA file. Here dropbox didn't allow to create a share link for the unc0ver IPA file. Even from dropbox main website. I got this error - 

<img width="1424" alt="Screenshot 2020-06-04 at 1 07 29 PM" src="https://user-images.githubusercontent.com/8479436/83728871-79e1c100-a664-11ea-92e2-9c672d2095ad.png">

Here the more details about the same on this thread - https://www.dropboxforum.com/t5/Dropbox-files-folders/You-don-t-have-permission-to-create-link-to-this-content/td-p/403086

As per this [reply](https://www.dropboxforum.com/t5/Dropbox-files-folders/You-don-t-have-permission-to-create-link-to-this-content/m-p/425239/highlight/true#M157903) on the thread, 

> I contacted Dropbox to file a support ticket. 
> I've found out that one of the files I was providing links to was aledgedly hosting a virus. For this reason my account had a link ban imposed.
> The solution for me was to either argue the presence of the virus or simply delete the file. I chose the latter as the simplest solution & will rehost that file elsewhere.
>I've also asked them to consider notifying users where this scenario occurs. Notification would have eliminated a lot of subsequent trouble and effort to get this resolved.

So, as we know unc0ver is a jailbreaking tool and contains some malicious files. That's why Dropbox flags this file and you can't share it with anyone else.

For now, I'm closing this issue. Feel free to open a new issue if someone gets this issue again. Because this time we'll get more details from AppBox.

Thank you :)

**Closed by vineetchoudhary** 2020-06-04 08:02 UTC
Labels: Confirmed Issue, bug
