### ISSUE TITLE
Errors produced at the HTTP layer. Please try again.

### ISSUE THREAD

**Issue by prashantsingh534** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#88] opened 2017-12-21 04:47 UTC
Errors produced at the HTTP layer. Please try again.

**Comment by prashantsingh534** [comment] 2017-12-21 04:48
When I successfully uploaded ipa file, after that I got this issue.Pls help..

**Comment by vineetchoudhary** [comment] 2017-12-21 06:26
Please logout your Dropbox account from AppBox. You can logout from AppBox menu Accounts> Logout Dropbox. And then login again. Also, please check your Dropbox space.

**Comment by viltorcheg** [comment] 2018-01-12 17:41
Hi! Dont work with 1,97 Gb IPA! With small IPA near 500 Mb all work fine!
Alert "Errors produced at the HTTP layer. Please try again.". 
I logout from my account and login again, but dont work!!! Please chekit! 
My LOG:
http://pastebin.ru/kop2CAhr

**Comment by vineetchoudhary** [comment] 2018-01-14 09:00
Hi @viltorcheg, found the issue. I'll fix this in next version. Hopefully before 20th Jan.

**Comment by viltorcheg** [comment] 2018-01-14 12:16
@vineetchoudhary  Thanx)))

**Comment by vineetchoudhary** [comment] 2018-01-15 17:20
Hi @viltorcheg, please try with pre-release version. I've tested this with 1.2 GB IPA. I'll release this publicly after more testing.

In this version, I'm uploading large size IPA file chunk. You can set chunk size from AppBox Preferences (⌘ + ,). Default size is 100MB, means AppBox will upload IPA file with 100MB partitions.

[Download from hereAppBox.app.zip](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/files/1632452/AppBox.app.zip)

**Comment by viltorcheg** [comment] 2018-01-16 18:48
Hi @prashantsingh534 
Bug alert:
454MB file IPA upload when i have alert! IPA in the link: https://cloud.mail.ru/public/8KRC/8bW2wBU3J
Appbox - Error
Appbox can't able to find Info.plist in you IPA.
In AppBox Preferences max size 150Mb! I have upload more then 150Mb! Do you try max size above 2-4Gb?

**Comment by vineetchoudhary** [comment] 2018-01-17 13:06
Hi @viltorcheg , please retry with this -> 
[AppBox.app.zip](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/files/1639051/AppBox.app.zip)

**Comment by viltorcheg** [comment] 2018-01-17 21:10
@prashantsingh534 
Thank you! Now I understand everything!
The program works! It uploads IPA files perfectly! Also Info.plist no error! File 2,3Gb upload fine without errors! Well done bro)))

**Comment by vineetchoudhary** [comment] 2018-01-19 05:42
[Released in 2.3.0](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.3.0)

**Closed by vineetchoudhary** 2018-01-19 05:42 UTC
Labels: Confirmed Issue, bug

**Comment by yogendrakarekar** [comment] 2018-05-29 13:22
Stiil shows the same issue "Errors produced at http layer, please try again"

**Comment by vineetchoudhary** [comment] 2018-05-30 05:17
Hi @yogendrakarekar , can you please provide the logs. You can see the logs generated by AppBox in `File>View Log`.

![screen shot 4](https://user-images.githubusercontent.com/8479436/30270562-a14e42fc-970a-11e7-9dd7-096d54eb1698.png)

**Comment by arshak-kahnputers** [comment] 2019-09-06 14:13
Please note that sometimes this error pops-up when you don't verify your DropBox account.

**Comment by vineetchoudhary** [comment] 2019-09-07 13:44
Hi @arshak-kahnputers, Nice finding. Thanks for putting this here. I found the same in the Dropbox official documentation [here](https://www.dropbox.com/developers/documentation/http/documentation#file_requests-create)

> File requests are only available on accounts with a verified email address. Users can verify their email address [here](https://www.dropbox.com/help/317).

**Comment by RajAggrawal0507** [comment] 2019-10-31 17:33
@vineetchoudhary  I am getting the same error on AppBox version 2.9.0(1).

<img width="422" alt="Screenshot 2019-10-31 at 11 02 59 PM" src="https://user-images.githubusercontent.com/38732747/67971336-9e8b3b80-fc32-11e9-810f-9b0977dfde0f.png">

**Comment by vineetchoudhary** [comment] 2019-10-31 19:08
Hi, can you please provide the logs. You can see the logs generated by AppBox in `File>View Log` or `⌘`+`L`.

<img width="456" alt="Screenshot 2019-11-01 at 12 36 36 AM" src="https://user-images.githubusercontent.com/8479436/67978311-d51b8300-fc3f-11e9-86e5-9089f31b10ea.png">

**Comment by MitulTalpara** [comment] 2020-04-11 07:00
Handling URL = db-mzwu8mq9xdtilpr://2/token#access_token=jr3Hcix_6JAAAAAAAAAAigXLZN6DJC2cpeBXIlwXFxTmkKhNOzHxP4H1HzCCIDjF&token_type=bearer&state=805C6343-F0A1-4A8A-BEDF-F4B3C63C8F8D-7007-000006B8B16A6067&uid=2597886912&account_id=dbid%3AAACqQjeO5kMBw-055onteXcqMBgqdAy8IFc
Success! User is logged into Dropbox.
Extracting Files...
Uploading - pa.ipa
Retrying (1) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (2) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (3) IPA Upload due to some error.
Uploading - pa.ipa
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - pa.ipa
Retrying (1) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (2) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (3) IPA Upload due to some error.
Uploading - pa.ipa
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - pa.ipa
Retrying (1) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (2) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (3) IPA Upload due to some error.
Uploading - pa.ipa
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - pa.ipa
Retrying (1) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (2) IPA Upload due to some error.
Uploading - pa.ipa
Retrying (3) IPA Upload due to some error.
Uploading - pa.ipa
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - pa.ipa
ALERT -
Title - Error Message - Errors produced at the HTTP layer. Please try again.
Extracting Files...
Uploading - pa-F19DF857-6E94-4CEA-A08A-16C4BA05D2E5.ipa
ALERT -
Title - Error Message - Errors produced at the HTTP layer. Please try again.

**Comment by vineetchoudhary** [comment] 2020-06-04 08:11
Hi All,

First of all, thank you very much for using AppBox. I added an automatic retry option for this issue. Also, if this occurs in the latest version ([2.9.1 or later](https://getappbox.com/download)) then AppBox will show more details about this.

For one case, I was successfully able to reproduce this issue with the unc0ver IPA file. Here dropbox didn't allow to create a share link for the unc0ver IPA file. Even from dropbox main website. I got this error - 

<img width="1424" alt="Screenshot 2020-06-04 at 1 07 29 PM" src="https://user-images.githubusercontent.com/8479436/83728871-79e1c100-a664-11ea-92e2-9c672d2095ad.png">

Here the more details about the same on this thread - https://www.dropboxforum.com/t5/Dropbox-files-folders/You-don-t-have-permission-to-create-link-to-this-content/td-p/403086

As per this [reply](https://www.dropboxforum.com/t5/Dropbox-files-folders/You-don-t-have-permission-to-create-link-to-this-content/m-p/425239/highlight/true#M157903) on the thread, 

> I contacted Dropbox to file a support ticket. 
> I've found out that one of the files I was providing links to was aledgedly hosting a virus. For this reason my account had a link ban imposed.
> The solution for me was to either argue the presence of the virus or simply delete the file. I chose the latter as the simplest solution & will rehost that file elsewhere.
>I've also asked them to consider notifying users where this scenario occurs. Notification would have eliminated a lot of subsequent trouble and effort to get this resolved.

So, as we know unc0ver is a jailbreaking tool and contains some malicious files. That's why Dropbox flags this file and you can't share it with anyone else.

Thank you :)
